name: Send Artist of the Week Email

on:
  schedule:
    # Run every day at 8:00 AM UTC
    - cron: '0 8 * * *'

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install dependencies
      run: cargo build --release

    - name: Send email with Artist of the Week
      env:
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        APP_URL: ${{ secrets.APP_URL }}
      run: |
        echo "Sending email with Artist of the Week..."
        cargo run --release --bin send_email