name: Send Artist of the Week Email

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug - Show workspace structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Project directory structure:"
        tree rust_project/hello_rust/

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Check time window
      id: time_check
      run: |
        CURRENT_TIME=$(date +%s)
        WORKFLOW_START_TIME=$(date -d "2025-05-15 00:00:00" +%s)
        TIME_DIFF=$((CURRENT_TIME - WORKFLOW_START_TIME))
        if [ $TIME_DIFF -gt 900 ]; then
          echo "should_run=false" >> $GITHUB_OUTPUT
        else
          echo "should_run=true" >> $GITHUB_OUTPUT
        fi

    - name: Build project
      if: steps.time_check.outputs.should_run == 'true'
      working-directory: ./rust_project/hello_rust
      run: |
        echo "Building in $(pwd)"
        cargo build --release

    - name: Send email
      if: steps.time_check.outputs.should_run == 'true'
      working-directory: ./rust_project/hello_rust
      env:
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        APP_URL: ${{ secrets.APP_URL }}
      run: |
        echo "Running in $(pwd)"
        cargo run --bin send_email